services:
  db:
    image: mysql:8.0
    container_name: demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
      TZ: Asia/Seoul
    ports:
      - "3307:3306"   # 로컬 3306은 네 PC MySQL, 도커는 3307로 사용
    command: ["mysqld","--character-set-server=utf8mb4","--collation-server=utf8mb4_general_ci"]
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: demo-app
    depends_on: [db]
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    environment:
      SPRING_PROFILES_ACTIVE: local,oauth
      TZ: Asia/Seoul

volumes:
  db_data:
